imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  null
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        schema_filter: ~^(orm_.*|migration_versions)~

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                filters:
                    sonatra_sharing:
                        class:      Fxp\Component\Security\Doctrine\ORM\Filter\SharingFilter
                        enabled:    true
        
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/Migrations"
    namespace: JudoIntranetMigrations
    table_name: migration_versions
    name: JudoIntranet Migrations

# Swift mailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# fxp security configuration
fxp_security:
    role_class: JudoIntranet\Entity\Role
    permission_class: JudoIntranet\Entity\Permission
    sharing_class: JudoIntranet\Entity\Sharing
    anonymous_role:
        enabled: true
    object_filter:
        enabled: false # Enable the object filter (optional)
    role_hierarchy:
        enabled: true # Enable the role hierarchy for organizational context (optional)
        cache: null # Defined the service cache for role hierarchy (optional)
    security_voter:
        role_security_identity: true # Override the Symfony Role Hierarchy Voter (optional)
        groupable: true # Enable to check the group in the Symfony Security Authorization Checker
    sharing:
        enabled: true
        identity_types:
            JudoIntranet\Entity\User:
                roleable: true # (optional)
            JudoIntranet\Entity\Role:
                permissible: true # (optional)
        subjects:
            JudoIntranet\Entity\Navi: private
    default_permissions:
        master_mapping_permissions:
            view:      read
            update:    edit
            create:    edit
            delete:    edit
    permissions:
        JudoIntranet\Entity\Navi:
            enabled: true
    doctrine:
        orm:
            object_filter_voter: true # Enable the Doctrine ORM Collection Object Filter (optional)
            listeners:
                permission_checker: true # Enable the Doctrine ORM Permission Checker Listener (optional)
                object_filter: true # Enable the Doctrine ORM Object Filter Listener(optional)
                role_hierarchy: true # Enable the Doctrine ORM listener of role hierarchy (optional)
                private_sharing: true # Enable the 'private' sharing filter type
                sharing_delete:  true # Enable the auto sharing delete when the entity is deleted
            filters:
                sharing: true # Enable the Doctrine ORM SQL Filter for sharing the entities (optional)
